### ISSUE TITLE
rawtherapee-5.0.ebuild GTK+ dependency

### ISSUE THREAD

**Issue by Beep6581** [vivo75/vivovl#1]
Hey

Regarding https://github.com/vivo75/vivovl/blob/master/media-gfx/rawtherapee/rawtherapee-5.0.ebuild#L35

Please note that RawTherapee does support all versions of GTK+ from 3.16 upwards. If possible, users/builders are encouraged to use 3.16-3.18 because of a scrollbar bug in 3.20-3.22.7, but that does not mean it should be impossible for people using GTK+ 3.20-3.22.7 to compile RawTherapee.

Kind regards

**Comment by vivo75** [comment]
yep, forgot that gtk+ 3.20 and upward were masked on my predominantly qt/plasma desktop ;)
