### ISSUE TITLE
Gentoo ebuild updates

### ISSUE THREAD

**Issue by Beep6581** [vivo75/vivovl#2]
Hello @vivo75 

I described some changes over at Gentoo's bugzilla, please see https://bugs.gentoo.org/show_bug.cgi?id=606896#c2

Kind regards

**Comment by vivo75** [comment]
see commit 
https://github.com/vivo75/vivovl/commit/79538bdc38ef46e28890bc84fe32fa0f978eb9ba
I still need to think about warning the users to enable -O3 and eventually chose the message

**Comment by Beep6581** [comment]
Re: https://bugs.gentoo.org/show_bug.cgi?id=606896#c3
I don't know how to add those messages/warnings.
I think the ebuild should inform the user that they're missing out on a significant speed boost if `-o3` is not set, and severely warn in scary red letters (or even fail) if `-ffast-math` is set that they gain nothing but will get artifacts.

**Comment by vivo75** [comment]
ok then, I've added a warn for the users not using -O3, it also point them to the documentation on how to do so.
`-ffast-math` is already forcefully _removed_ from {c,cxx}flags by previous commit, hopefully there are few users enabling that flag globally but just in case ...

this is commit 700a3968ec5d6ea953e1409ee3858ca2940fdb39

example output (the lines starting with an asterisk "*")
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
>>> Verifying ebuild manifests
>>> Running pre-merge checks for media-gfx/rawtherapee-5.0
 * upstream suggest using {C,CXX}FLAGS+="-O3" for better performances
 * see bug#606896#c2
 * take a look at https://wiki.gentoo.org/wiki//etc/portage/package.env
 * for suggestion on how to change environment for a single package

>>> Emerging (1 of 1) media-gfx/rawtherapee-5.0::vivovl
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
